name: Ingest Manuals

on:
  workflow_dispatch:
  push:
    paths:
      - 'manuals/**.pdf'

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Build vectorstore
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/ingest.py
      - name: Commit and push vectorstore
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add vectorstore.pkl
          git commit -m "Update vectorstore [skip ci]" || echo "No changes"
          git push
