name: Ingest Manuals

# Maak expliciet write-rechten aan voor deze workflow
permissions:
  contents: write       # nodig om vectorstore.pkl te committen en pushen
  actions: read         # standaard leesrechten voor actions

on:
  workflow_dispatch:
  push:
    paths:
      - 'manuals/**.pdf'

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false
          # ensure the GITHUB_TOKEN is used for git push
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Build vectorstore using HuggingFaceEmbeddings
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: python scripts/ingest.py

      # ───────────────────────────────────────────────────────────────────────
      # Als je ooit weer OpenAI-embeddings wilt gebruiken,
      # comment de HF-stap hierboven uit en haal hieronder de # weg:
      #
      # - name: Build vectorstore using OpenAIEmbeddings
      #   env:
      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      #   run: python scripts/ingest.py
      # ───────────────────────────────────────────────────────────────────────

      - name: Commit and push vectorstore
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f vectorstore.pkl
          git commit -m "Update vectorstore [skip ci]" || echo "No changes"
          git push
