name: Ingest Manuals

on:
  workflow_dispatch:
  push:
    paths:
      - 'manuals/**.pdf'

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt
      # ─── debug stap ────────────────────────────────────
      - name: Debug HF token presence
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: |
          echo "HF_API_TOKEN is set? ${HF_API_TOKEN:+yes}"
      # ────────────────────────────────────────────────────
      - name: Build vectorstore using HuggingFaceEmbeddings
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: python scripts/ingest.py

      # ───────────────────────────────────────────────────────────────────────
      # Als je ooit wilt terugschakelen naar OpenAI-embeddings,
      # comment hierboven de HF-stap uit en haal hieronder de # weg:
      #
      # - name: Build vectorstore using OpenAIEmbeddings
      #   env:
      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      #   run: python scripts/ingest.py
      # ───────────────────────────────────────────────────────────────────────

      - name: Commit and push vectorstore
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add vectorstore.pkl
          git commit -m "Update vectorstore [skip ci]" || echo "No changes"
          git push
