name: QA Bot

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]

jobs:
  answer:
    if: >
      github.event_name == 'issue_comment' ||
      (github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'ask'))
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Answer question
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/answer_issue.py
